language: node_js
node_js:
   - "5"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bundle install
  - bower install
  - grunt prod
notifications:
  email: true
# Taken from:  https://github.com/mdix/es6-babel-browserify-karma-boilerplate/blob/master/.travis.yml#L3

#trying test
